import { Metadata } from "next";

export const metadata: Metadata = {
    title: "Add Brands",
    description: "Generated by create next app",
};


export default function AddBrandLayout({
    children
}: {
    children: React.ReactNode
}) {
    return (
        <div>
            {children}
        </div>
    )
}