import React from "react"

export const metadata = {
    title: 'Register',
    description: 'Generated by Next.js',
}

export default function RegisterLayout({
    children
}: {
    children: React.ReactNode
}) {
    return (
        <div>
            {children}
        </div>
    )
}