export const metadata = {
    title: 'About Page',
    description: 'Generated by Next.js',
  }

export default function AboutLayout({
    children
}: {
    children: React.ReactNode
}) {
    return (
        <>
            <h1>This is an inner layout of about</h1>
            <div>
                {children}
            </div>
        </>
    )
}