import { Metadata } from "next";

export const metadata: Metadata = {
    title: "Brands",
    description: "Generated by create next app",
};

export default function BrandsLayout ({
    children
}: {
    children: React.ReactNode
}) {
    return (
        <div>
            {children}
        </div>
    )
}